### ISSUE TITLE
Show files without subfolders

### ISSUE THREAD

**Issue by Trinsec** [ozntel/file-tree-alternative#10]
If I understand this plugin correctly, files from all subfolders will be shown along with the files of the currently active folder if you're in the file view. Is there a way to only show the files of the currently active folder? For example, I have a few files in the root folder, but can never seem to find those because I see every file from everywhere. Is there a setting/toggle for this that I overlooked?

**Comment by ozntel** [comment]
I just release a version, which includes a toggle in the plugin settings. Please update the plugin to see the changes

**Comment by Trinsec** [comment]
Neat! That certainly helps! I wonder if it could be a quicker toggle than going all the way to the config? Hotkeyable, for example?
