### ISSUE TITLE
Feature Request: Create folder note automatically if it does not exist

### ISSUE THREAD

**Issue by trevordebard** [ozntel/file-tree-alternative#100]
Would there be any interest in changing the default folder note behavior to create automatically if one does not exist? I would be open to creating a pull request if it would be a welcome change. 

Alternative Options:
- keyboard shortcut to open folder note
- ??

**Comment by pcause** [comment]
+1 it is hard to create folder notes with an index.  If I shift+click I get the error message about no note.  I have to manually create the note and then drop a template in that uses another plugin to create the content.  What is the world does this options really do other than open the note if it exists?  Pretty useless.

**Comment by ozntel** [comment]
It is available in the new release
