### ISSUE TITLE
Created new note from template appears in side pane

### ISSUE THREAD

**Issue by ih8snow** [ozntel/file-tree-alternative#102]
Hi,
when I:
right click a folder in the side pane and select "create new note from template"
- the new note is opened in the side pane and not in the main window.

Even worse.. it replaces the icon from "file tree view" with the “untitled” icon from the new note.
Closing this icon - then there is no file tree icon any more.

**Comment by ozntel** [comment]
It is the option coming from the Templater plugin. I don't have control over it. Please open the issue for the relevant plugin. If you try to "create new note from template" within the default file explorer, you will have the same
