### ISSUE TITLE
Scrolling a file post on the iPhone is very difficult

### ISSUE THREAD

**Issue by mlevison** [ozntel/file-tree-alternative#105]
When I attempt to scroll through a list of files on an iPhone the context menu for copy/delete/move almost always pops up. This makes the plug-in difficult to use on the iPhone.

**Comment by edconway** [comment]
I have also this encountered this problem - I guess associated with the long press functionality on iOS

**Comment by ozntel** [comment]
It should be resolved in the new release

**Comment by edconway** [comment]
Great. Thank you!
