### ISSUE TITLE
[FR] Option to see notes outside of a folder

### ISSUE THREAD

**Issue by wharjack** [ozntel/file-tree-alternative#108]
Hi, I think it's hard to see the new note that I created because it doesn't have a folder

![tempsnip](https://user-images.githubusercontent.com/52787179/189490073-9f1cd180-5059-4e6c-9973-3f57dfa967bc.png)

Also, please have an option to remove the shadow and the white background because it doesn't fit to a theme

**Comment by ozntel** [comment]
If you click Vault Name in the folder view, it should show you the files that are directly under the vault. Use the eye icon to hide/unhide children folder content.
Also removed box shadow in the last release
