### ISSUE TITLE
Folder name is not visible in themes with light editor pane and dark nav pane

### ISSUE THREAD

**Issue by iiz00** [ozntel/file-tree-alternative#11]
When I use a CSS theme in which editor pane has lighter background color and file navigation pane has darker color such as Red Graphite or Dark Graphite Pie (light mode), folder name is not visible. File name has no problem. The color of folder name seems to be determined by `--text-normal`.
Is there any way to use your plugin with such themes?

**Comment by ozntel** [comment]
I just release a version, which includes `oz-folder-name` class for the folder names. You can include it in your custom CSS snippets.

**Comment by iiz00** [comment]
Thank you for the update!
Now I can see the whole list by changing the color of `oz-folder-name` and `oz-file-tree-header`.
