### ISSUE TITLE
FR: Previews in File Explorer

### ISSUE THREAD

**Issue by Calorion** [ozntel/file-tree-alternative#110]
When I saw "Evernote mode," I got excited thinking that that meant that this plugin would show note previews in the File Explorer like Evernote does. It's often very hard to remember what was in what file, especially for Daily Notes. Could this feature be added?

**Comment by ozntel** [comment]
You can hover on name of the file keeping pressed CTRL or CMD button and it should show you the preview. Make sure that you enable from the settings.

**Comment by Calorion** [comment]
Unfortunately I'm on mobile.
