### ISSUE TITLE
Search by tag doesn't find tags in YAML

### ISSUE THREAD

**Issue by upnix** [ozntel/file-tree-alternative#111]
The "Search File by Name or Tag" function will not find notes with a specific tag if that tag only exists in the YAML front matter.

# Recreate
1. Create a folder with two notes, one with the tag "#TestTag" in the body, the second with `tags: ["TestTag"]` in the YAML front matter.
2. Using the "Search File by Name or Tag" function, search for TestTag: `tag:TestTag`
3. Only the file with the tag in the body should appear.

# Behaviour expected
I'd expect that the note with the tag in the YAML would also appear in a tag search.

**Comment by ozntel** [comment]
@upnix it should work in the new release (v.2.2.8). Thanks for the coffee by the way :)
