### ISSUE TITLE
[FR] Move file command

### ISSUE THREAD

**Issue by AtlcatlQ** [ozntel/file-tree-alternative#112]
I would like a command that allows me to switch off the native file explorer plugin. I use a lot the "File Explorer: Move file to another folder" command from the File Explorer native plugin. But it's the only case where I use the native plugin.

**Comment by ozntel** [comment]
Is this command still in use in Obsidian? I can not see when I search for it

**Comment by AtlcatlQ** [comment]
Oh, yeah, sorry, they have moved out from the file native plugin, it works without the plugin. Now it's not even "file explorer", instead is called only "files".

However, Thanks for the plugin
