### ISSUE TITLE
[FR] Images Drag and Drop

### ISSUE THREAD

**Issue by aldaw** [ozntel/file-tree-alternative#113]
**How it behaves.**

![](https://user-images.githubusercontent.com/16668679/194788466-d3382c65-81e0-429d-81b4-b9b488cc3feb.mov)

**How I expect it to behave, and how it's done out of the box in Obsidian.**

![](https://user-images.githubusercontent.com/16668679/194788472-b9b6fa6c-86f8-4f92-a497-be01c487d01d.mov)

**Thank you for all your time you have put in!**

**Comment by waltcf** [comment]
I believe what they mean is OFTA does not permit dragging and dropping files into folders. I have encountered this limitation a few times already and was bummed to have to revert to the default file tree to organize my files.

**Comment by cbertero** [comment]
Hello

Drag and drop works only when you are drag, go to the main note view and then go back to the file tree to drop wherever you want.

It's not a big issue but it would be nice if it was fixed.

Thanks !

**Comment by ozntel** [comment]
> How I expect it to behave, and how it's done out of the box in Obsidian.

In the new version, the dragged image should do exactly the same as the default file explorer. 
Let me know if you still have issues. 
Thanks
