### ISSUE TITLE
In Obsidian 1.0, "open in new pane" in right click menu only opens in new tab

### ISSUE THREAD

**Issue by jrphilipyang** [ozntel/file-tree-alternative#116]
If I click "open in new pane" in right click menu, the file will only opens in new tab, not new pane. 

I cannot file a simple method to open a file in new pane using file-tree-alternative. The effect of Ctrl + Alt + click on a file should be openning in a new pane, not a new tab. (The original File List in Obsidian opens a file in a new pane if I Ctrl + Alt + click on a file. I think file-tree-alternative should do the same ?)

Note: the word "pane" is now replaced by "tab group" in obsidian 1.0. But I will still use "pane" to mean a visually separated space in obsdian. I.e., you can see the content of multiple panes at the same time but for multiple tabs, you can only see their titles at the same time.

**Comment by ozntel** [comment]
Please update the plugin. It should work properly now
