### ISSUE TITLE
Doesn't properly Fire the event to signal selecting a folder

### ISSUE THREAD

**Issue by drventure** [ozntel/file-tree-alternative#117]
As a result, if you install the Folder Notes plugin, and set it to display the Folder note when the Folder is clicked, nothing happens.

Whereas the built in Tree view DOES automatically display the folder note when you simply click the Folder.

Of course, if there is no folder note, then nothing should happen either.

**Comment by ozntel** [comment]
You need to use Shift + Click. It is described in the plugin settings:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/55187568/197602901-9f4b4661-655e-47dd-84e5-dcbdc66b4f9f.png">

The single click is assigned to show the list of the files under a folder. The main purpose of the plugin is to list folders and files so i am not planning to assign single click to some other actions. 

Hope it makes sense

**Comment by drventure** [comment]
Thanks for the quick reply.
I didn't realize File Tree Alternative ALSO had the folder note ability.
There's a different plugin called "Folder Note" that I'd enabled for that.

You are correct. It works just fine via Shift and click.

I guess my thought on that is... maybe make it an option to open the folder
note on Shift click or simply just click?

But either way, File tree alt is very nice. Just feels better than files
and folders all jumbled up like the default view.

Thanks again!
Darin
