### ISSUE TITLE
Notes texts are slightly blurred since last update.

### ISSUE THREAD

**Issue by LudwigArisleib** [ozntel/file-tree-alternative#119]
I can't tell if it's the last Obsidian 1.00-1.03 or File-tree-alternative 2.2.4 update, but notes texts are slightly blurred since.
I didn't have this problem before one of these updates for sure.

I did an elimination test on all the plugins I had installed by desactivating and reactivating, and found that only this plugin made the notes slightly blurred, which makes the reading quickly unpleasant and the plugin unusable.

I can reproduce this problem easily by just deactivating and reactivating this plugin.

Using Windows 10.

**Comment by ozntel** [comment]
It might be related to a theme you are using or CSS snippets you are using. The plugin itself by default shouldn't cause any blurry text/image etc. You can switch back to the default theme and disable your snippets to see if it helps. In case the issue persists, let me know. Thanks
