### ISSUE TITLE
[Question / Feature Request] Split Folder Tree and File List

### ISSUE THREAD

**Issue by alexgeirby** [ozntel/file-tree-alternative#12]
Hello @ozntel! Thank you for this great plugin. But when I started using it, I was hoping that the folder tree and the file list would be displayed in the sidebar separately, one above the other, rather than splitting the same display area.
Did I miss something? Is there any setting now for displaying folders and files in different display areas? If not, would you consider implementing such a feature in the next releases of your awesome plugin?

**Comment by ozntel** [comment]
Please kindly refer to corresponding part of README:

https://github.com/ozntel/file-tree-alternative#old-version-evernote-style
