### ISSUE TITLE
hover in file list does't bring up preview

### ISSUE THREAD

**Issue by pcause** [ozntel/file-tree-alternative#121]
In the file list if I hover and then hit ctrl I don't get the preview.  I am using 1.0.3

**Comment by ozntel** [comment]
Normally if you enable the hover preview option from the plugin settings and hover on a file name with CTRL or CMD key used, it has been working. However, the plugin was not capturing the CTRL/CMD buttons during the hover process, it should work now. Please update the plugin to v.2.2.6. Thanks
