### ISSUE TITLE
New notes are created on the left pane where the file tree is located 

### ISSUE THREAD

**Issue by gerroon** [ozntel/file-tree-alternative#125]
Hi

I have been using this plugin for a while, it is so great. However it seems like this is not working so well with 1.0.3 on Windows. When I create a new note using the this plugin's "(+)" to create a note in the currently selected folder, the new note opens in where the file tree normally is (the left side of the Obsidian window), so it takes over its space. I do not why that is the case. I never had this issue with the previous versions of Obsidian.

Is this a big with the plugin or a setting issue with Obsidian?

**Comment by ozntel** [comment]
Please make sure that you use the latest version of the plugin, which is v.2.2.6 and also latest version of Obsidian. 
After Obsidian implemented tabs, the way how new panes are created changed. If you don't update both, you might have unexpected issues like the one you mentioned. Thanks!
