### ISSUE TITLE
"Open in System Explorer" doesn't work

### ISSUE THREAD

**Issue by dummifiedme** [ozntel/file-tree-alternative#13]
Trying to open with Open in System Explorer in the Folder's Context menu, produces no outcome.

**Comment by ozntel** [comment]
I just tried and it should work properly. 
I am using the default context menu of Obsidian, and there is no custom menu for `Open in System Explorer` in the plugin. Please also try within the default `file explorer` if it works.

**Comment by ozntel** [comment]
I am closing the issue. Please let me know if the issue persists.
