### ISSUE TITLE
[Feature request] enter the edit mode creating a new file

### ISSUE THREAD

**Issue by dawnlh** [ozntel/file-tree-alternative#140]
Thanks for the wonderful tool! I have a small question:

When I use the `create a note` button to create a new file and input its name, the new file will be opened with the read mode.  But in fact, after I create the file, the next thing is generally to type something in it. So it will be convenient to open the created file with edit mode. I'm not sure whether it depends on other settings. I try to set the obsidian editor's general setting and enable `enter edit mode in new tab`, but it doesn't work.

**Comment by ozntel** [comment]
This plugin respects the default settings. To be able to change the behavior, go to the **Obsidian Settings > Editor** and change the **Default View for New Tabs**  to Editing View.
