### ISSUE TITLE
[Enhancement] Allow manually reorder the files or folders

### ISSUE THREAD

**Issue by Shuusei04** [ozntel/file-tree-alternative#15]
I hope there is such functionality to sort order the files or folders on our own preferences. For example, I could put the file "test" between "Untitled 5" and "Untitled Kanban ."
![image](https://user-images.githubusercontent.com/52666628/123896717-06ac9a80-d99d-11eb-86bb-e6bc689ec30c.png)

A similar function in marginnote may be a  prototype.
<img width="335" alt="CleanShot 2021-06-30 at 12 22 08@2x" src="https://user-images.githubusercontent.com/52666628/123897149-ddd8d500-d99d-11eb-96b9-50d48fbf9c61.png">

**Comment by ozntel** [comment]
Hi, I don't have a plan to implement reorder for the moment. However, you can use the function of `pinning` on the top in order to differentiate the files you want to have always under your hand. Thanks for the suggestion!
