### ISSUE TITLE
[Feature Request] Clicking to expand folder should also change to folder

### ISSUE THREAD

**Issue by deafpolygon** [ozntel/file-tree-alternative#151]
Clicking on the icon to expand the folder list should activate the folder in the filelist.

It would be nice to add an option to do so, because often I will look into a folder by expanding it, but the file list is still on the previously selected folder and expanding the folder list doesn't change or update it.  I.e. 

I have three folders:  

\> Books
\> Games
\> Movie

Inside each folder, I might have additional folders:

\> cover
\> notes
\> reviews

If I click directly on Books, it does not expand, and the file list is updated. This is expected behavior.  If I expand Games so now I get
\> Books
v Games
&nbsp;&nbsp;&nbsp;\> cover
&nbsp;&nbsp;&nbsp;\> notes
&nbsp;&nbsp;&nbsp;\> reviews
\> Movie

The file list still displays notes from Books, and not from Games. I would like an option where the file list would change to the newly expanded folder as if I also clicked on it directly.

**Comment by wallypg** [comment]
Alternatively, I think it would be better to leave it as is, but if you double click on the folder name, it both opens and focuses on the folder so you can see at the same time the folders and the files in the bottom panel.

**Comment by ozntel** [comment]
You can now use the double-click option to focus on the folder. It also activates the folder in the file pane.
