### ISSUE TITLE
[Enhancement] Split into two panes (folders and notes)

### ISSUE THREAD

**Issue by andi0b** [ozntel/file-tree-alternative#16]
Quiver (https://happenapps.com/) or Joplin have a two-level navigation. On one pane you chose the folder and on another pane you see all the notes.

I would like that much more, than the current version where you use just one pane and you always need to click the back button to switch folders.

**Comment by ozntel** [comment]
Please kindly refer to the corresponding part of README:

https://github.com/ozntel/file-tree-alternative#old-version-evernote-style

**Comment by ozntel** [comment]
Duplicate #12

**Comment by andi0b** [comment]
Could you please add an open source license to this project so I could fork it? :)
