### ISSUE TITLE
Canvas can not be used as folder note, yet does not appear in file list as if it is a folder note

### ISSUE THREAD

**Issue by technotherion** [ozntel/file-tree-alternative#166]
1. Enable Folder Notes in File Tree Alternative - preferably with folder note arrows on 
2. Create a folder named Folder1 
3. Create a canvas named Folder1.canvas
4. Folder1.canvas should disappear from the file listing, but no arrow will appear next to Folder1 to indicate that it has a folder note. 
5. Shift+click on Folder1to create a folder note, folder1.md will be created
6. In the file listing, neither folder1.md nor folder1.canvas will be seen
7. In the default file tree, I can see that both files are still inside of the folder, but that opening the folder note will always open folder1.md

**Comment by ozntel** [comment]
This will be available in the next release
