### ISSUE TITLE
Folder Notes 'disappear' when folder is renamed

### ISSUE THREAD

**Issue by capybarahero** [ozntel/file-tree-alternative#167]
Hey there, thanks for the nice plugin! 
I recently started both Obsidian and the plugin, and I noted that folder notes are not renamed automatically.

## Steps to reproduce: 
1. Turn Folder Notes on;
2. Create a new Folder Note;
3. Rename the folder

The Folder Note arrow reference will disappear since the hidden note hasn't been renamed.

Not sure if it's a bug or an upcoming feature, but decided to share it here
Thanks

**Comment by ozntel** [comment]
It should update the folder file name, as well. Thanks
