### ISSUE TITLE
[Enhancement] Little cross in search box

### ISSUE THREAD

**Issue by DutchPete** [ozntel/file-tree-alternative#17]
Hi Ozan, I installed the plug-in 2 days ago after Chetachi inadvertently drew my attention to it with a GIF she posted in the csschannel. I like this plug-in, find it a useful addition.

I use the search box regularly, and 1 thing I would like is to have a little cross to delete the search term easily, like in the main file explorer search box.

![image](https://user-images.githubusercontent.com/10794265/124415237-19d4b700-dd5d-11eb-8f25-ec333ba017a8.png)

**Comment by ozntel** [comment]
Hi, please update the plugin from Community Plugins. The feature is included in the new version.

**Comment by DutchPete** [comment]
Thanks a lot, Ozan.
