### ISSUE TITLE
Issue with folder names on iPad

### ISSUE THREAD

**Issue by kimaldis** [ozntel/file-tree-alternative#173]
I have a vault, synced between an iPad and a Macbook. Folder names on the Macbook are a nice, visible white but on the iPad they're a grey that nearly matches the background, to the extent that I can't read them. Any idea what might be causing this?

thanks
![IMG_0160](https://github.com/ozntel/file-tree-alternative/assets/4265299/d66bdfef-6c4f-4bbf-9ff4-e7b35c57dcf7)

**Comment by ozntel** [comment]
It depends on the theme you are using. I advise installing the "Style Settings" plugin. I made sure that File Tree Alternative is compatible and you should be able to adjust the folder and file name color. Thanks
