### ISSUE TITLE
Icons from Iconize don't appear in FileTreeAlternative

### ISSUE THREAD

**Issue by mlevison** [ozntel/file-tree-alternative#176]
Not sure where to ask for help/fix. Iconize makes my vault look nice. 

FiletreeAlternative makes my folders behave like a sensible finder. How could we tweak filetree to pay attention to the icons from Iconize?

**Comment by jvdevlab** [comment]
+1 This would be great. I use Iconezer rules to place icons on folder automatically along with your plugin this helps navigating large folder trees.

**Comment by jvdevlab** [comment]
This is actually a dupe of https://github.com/ozntel/file-tree-alternative/issues/109 which has more upvotes.
