### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by luckman212** [ozntel/file-tree-alternative#18]
Hi @ozntel 
This is an awesome plugin!
Thank you.

One small thing I noticed, in settings you forgot to change description from Clear Unused Images plugin...
https://github.com/ozntel/file-tree-alternative/blob/3581a5d0165a03c9968c801193d9d96d1b2bf594/src/settings.ts#L47

**Comment by ozntel** [comment]
Hi, thanks for noticing. I just corrected and included the change within the new release
