### ISSUE TITLE
"Reveal Active File" stopped working with most recent updates of file-tree-alternative

### ISSUE THREAD

**Issue by korm** [ozntel/file-tree-alternative#181]
(posted Dec 04, 2023)

After the most recent updates of file-tree-alternative, the "Reveal Active File" button does nothing.   I have removed and re-added the plugin, toggle settings, force-reloaded Obsidian, etc., and the button does not work.

**Comment by ozntel** [comment]
You are right, i made a lot of breaking changes to improve performance and it touched a lot of components. I just fixed the Reveal Active File part. It should work now in the latest release 2.4.2. Let me know in case you realize any other issues. Thanks

**Comment by korm** [comment]
Fixed in 2.4.2.  Confirmed.  Thank you!
