### ISSUE TITLE
[Feature request] no drag and drop files?

### ISSUE THREAD

**Issue by tkossak** [ozntel/file-tree-alternative#189]
It doesn't have basic features from default file tree - moving files by drag and drop. Any plans about introducing it? Thank you.

**Comment by jvdevlab** [comment]
Would be great. Right-clicking and selecting Move to... works but problematic with large folder structure.

**Comment by ozntel** [comment]
This should work now. Just fixed in the new release

**Comment by jvdevlab** [comment]
Just tired it. Thank you!

**Comment by tkossak** [comment]
Thank you very much!
