### ISSUE TITLE
allow display of file in root folder

### ISSUE THREAD

**Issue by knodalyte** [ozntel/file-tree-alternative#19]
Files in the root folder are not included in the file list nor are they included in search results, even if the "all:" syntax is used.

Maybe there could be a setting or toolbar button to toggle this?

**Comment by ozntel** [comment]
Actually, they are included. I just created a few files in the root folder and searched with "all:" syntax and they are visible in the search result. 
Are you sure the files you are searching for don't have extensions provided in the `excluded file extensions` settings?

**Comment by knodalyte** [comment]
Sorry, I was mistaken about how the plugin works. I did not realize that files were not displayed in the file tree, but only if I click on the folder name. Now I see that everything is working correctly.
