### ISSUE TITLE
Pin to top not working anymore

### ISSUE THREAD

**Issue by Horatiu-V** [ozntel/file-tree-alternative#191]
Sometimes the pin to top notes are lost when restarting Obsidian. For a few days now, pin to top no longer works at all, I can’t pin any notes.

File Tree 2.4.0
Obsidian 1.4.16

**Comment by ozntel** [comment]
You are right. The new release should fix the issue. Let me know if the issue persists. Thanks! 

Related Commit: https://github.com/ozntel/file-tree-alternative/commit/c835f8f52b0d5c9b376ab8faa3e877dbf2a691e2
