### ISSUE TITLE
on "Create a Note" do not prompt with "untitled"

### ISSUE THREAD

**Issue by korm** [ozntel/file-tree-alternative#192]
When clicking the "Create a File" plus-sign icon, FTA opens a dialog populated with the word "untitled" and the cursor is at the end of that word.  So, we have to "select all" and delete or backspace over "untitled" to get rid of it.  Since creating a note named "untitled" is never much use (granted, Obsidian by default does that), it would be helpful if FTA either provided the dialog with no text shown (preferred), or provided the dialog with "untitled" selected so we can overtype it.

**Comment by ozntel** [comment]
The last release should now pre-select the untitled text

**Comment by korm** [comment]
Yes, confirmed.   Thank you!
