### ISSUE TITLE
Title Header is too light in light mode

### ISSUE THREAD

**Issue by chetachiezikeuzor** [ozntel/file-tree-alternative#2]
This plugin looks really incredible and I can't wait to see your next update with it. I don't know if these changes will be made in your next release but I noticed that the title header is too light for light mode. I see that the class `.oz-file-tree-header`'s color property is set to `text-on-accent`. I think setting it to `text-normal` would be better for both light and dark mode. 

<img width="287" alt="Screen Shot 2021-06-11 at 11 26 34 AM" src="https://user-images.githubusercontent.com/79069364/121718795-4d972680-caa8-11eb-8163-e09c6f7c2e22.png">

**Comment by ozntel** [comment]
Hi @chetachiezikeuzor just release a version, in which I corrected the CSS issue :)
