### ISSUE TITLE
How can I see files in the root?

### ISSUE THREAD

**Issue by mike2003** [ozntel/file-tree-alternative#20]
I do not see anything there, just files are not shown, only folders. This is strange.

**Comment by ozntel** [comment]
Please check the plugin details. You can see demo in the video https://youtu.be/i3Ly06IurCA and the other videos shared in plugin details.
You need to click and open the file list view for each folder

**Comment by mike2003** [comment]
I think you misunderstood me. I'm talking about the ROOT folder! If I select root, I see all files in all folders. What for?? Probably this can be useful too, but I can't find the notes I need in this heap!

**Comment by ozntel** [comment]
![image](https://user-images.githubusercontent.com/55187568/128645616-a9bc4b29-ec56-4fd2-b6f7-c839e0e296d1.png)

**Comment by mike2003** [comment]
Standart https://i.imgur.com/LwWklsB.jpg
https://i.imgur.com/1vwqMzO.jpg

**Comment by mike2003** [comment]
https://i.imgur.com/rZu4n8p.jpg

**Comment by ozntel** [comment]
Firstly read the documentation! Turn off include files from subfolders.
Secondly, if you don't think the plugin is useful, just please do not use. You'd be a way better with the default explorer.

**Comment by mike2003** [comment]
This is all strange. Don't show notes at all or show a big useless bunch! Probably right it should be split it for the root.

And the function of creating a new note is broken too. The name has no default focus, and then text input does not work.

**Comment by ozntel** [comment]
Thanks for your feedback. You should keep using the default file explorer, then. Cheers!
