### ISSUE TITLE
Insert image link instead obsidian URL when dragging image

### ISSUE THREAD

**Issue by vgyenge6** [ozntel/file-tree-alternative#205]
Hi, 

This is a great plugin. Thanks for developing it.

I noticed when I drag an image the obsidian URL will be inserted.
It would be much better to get an image link rather obsidian URL.

Thanks for considering this change.
![Dragging_image_will_insert_obsidianURL_2024-02-07](https://github.com/ozntel/file-tree-alternative/assets/100508773/592c2d41-3d59-42db-b6b9-598fb41d6c41)

**Comment by ozntel** [comment]
It was a bug and it should be fixed by now within previous releases. When you drag an image or a note, it should insert an internal link now. Thanks!

**Comment by vgyenge6** [comment]
Thank you for dealing with this issue and resolving it. I checked and that works well now. 

Further good work for you.
