### ISSUE TITLE
The highlighted folder of selected file is quite obviousness! The folder is only slightly bold.

### ISSUE THREAD

**Issue by cruisermaxx** [ozntel/file-tree-alternative#212]
As the title described, the color for folder of selected file is not obvious.
Please consider highlighting it heavily~

**Comment by ozntel** [comment]
It might be overwritten by a theme you are using. The default selected file or folder weight is pretty visibly bold. You can also consider installing the Style Settings plugin (for which I already extended the CSS code) and setting the color to something more distinguishable:

<img width="520" alt="image" src="https://github.com/ozntel/file-tree-alternative/assets/55187568/bbc363bf-af55-4907-9cf0-cabf6843243b">

**Comment by cruisermaxx** [comment]
Thank you very much for replying and give a solution!
