### ISSUE TITLE
REGRESSION: VERSION 2.5.2 drag and drop images: drops obsidian url scheme, not wikilinks, as previously (2.3.4) did

### ISSUE THREAD

**Issue by ksdavidc** [ozntel/file-tree-alternative#213]
UPDATE: this is a regression. see the comment below https://github.com/ozntel/file-tree-alternative/issues/213#issuecomment-2031768333

Dragging from filetree is no longer giving wikilinks, but obsidian url scheme.
Dragging with the regular file explorer works as expected.
Using 1.5.8 with the 1.5.8 installer.

https://github.com/ozntel/file-tree-alternative/assets/62230004/30237bfd-67d7-4bb5-9ee1-431153f3bb44

**Comment by ksdavidc** [comment]
PS this has been confirmed with obsidian sandbox vault with just filetree installed.

**Comment by ksdavidc** [comment]
I have done more research on this and it is clearly a regression in version 2.5.2. 

**reverting to version 2.5.1 removes the error.**

Also, clarification, this is just for images (jpg, svg, excalidraw). 

I am using a mac, with obsidian 1.5.12 and installer 158.

In addition, it is creating just the url scheme text "link", but not a link "![[file]]"  as was usually created.

Dragging and dropping regular  markdown md files works correctly.

**Comment by ksdavidc** [comment]
Attached sandbox vaults with 2.4.4 (gives error in console), 2.5.3 (pastes obsidian link, no error), and 2.3.4 (works as I would like it to)
[File Tree Vaults.zip](https://github.com/ozntel/file-tree-alternative/files/14939572/File.Tree.Vaults.zip)

**Comment by ozntel** [comment]
It should be fixed in the new release v.2.5.5 
Let me know in case you encounter the same issue. 
Thanks

**Comment by ksdavidc** [comment]
Chef's kiss (and fingers crossed). Sorry for the all caps. It wasn't annoyance, just surprise. For the longest time I was certain this was a conflict with another plugin, and I spend quite some time reconstructing several vaults from scratch before I felt fairly confident (but astonished!) the error was here and so long-lived. I really appreciate the plugin, and it's probably the most used among the hundred or so I depend on more than I should. Now if you could implement multi-select, that would be chef's...genuflect. :-)
