### ISSUE TITLE
Cannot Rename Folder

### ISSUE THREAD

**Issue by Steven8Tang** [ozntel/file-tree-alternative#216]
Found that the folder name cannot rename.

One more suggestion,
if the Evernote Like View, the file list can be auto show / hide by mouse cursor hover or folder choosing.  Because the size of screen is too small.

**Comment by ozntel** [comment]
Rename folder functionality should be fixed in the last release. Let me know if you still have the same problem. 

I would recommend disabling the Evernote View. It will display the list of files only once you select any folder. Thanks
