### ISSUE TITLE
Links are misplaced everywhere

### ISSUE THREAD

**Issue by snird** [ozntel/file-tree-alternative#22]
I can't figure out why, but it happens too often and its weird
Links for other folders appear where you don't expect them

![image](https://user-images.githubusercontent.com/2139589/132985259-6d487433-2101-4c8b-a726-7c9cc4bfd2bc.png)

This is one example, as you can see in the image with the debug console, the "REIT" folder link appears there

The actual folder of "REIT" exists, like 50-60px below.
So it seems like in this case it got shifted up for some reason

**Comment by ozntel** [comment]
Are you using the updated version 1.3.9?

**Comment by snird** [comment]
Updated now, it fixed it.
I was sure I'm on the latest version.
Thank you
