### ISSUE TITLE
[Bug or Feature?] Note no longer pinned after name change

### ISSUE THREAD

**Issue by Horatiu-V** [ozntel/file-tree-alternative#226]
Hello,

If I change the name of a pinned note, that note will no longer be pinned. If I change it back, the file will be pinned again. 

Is this a feature or a bug? 

For me would be useful for a note to remain pinned if I change it's name.

PS1 Thank you for this plugin, it's very useful to me!
PS2 Custom folder (and files) order will be another big improvement IMHO.
PS3 The modification to support File Order plugin that houcheng did, is good enough.

**Comment by ozntel** [comment]
Yeah, you are right, it was not implemented actually. I just pushed a new release with a fix. It should capture any changes and keep the pinned file accordingly. Thanks!
