### ISSUE TITLE
Control the height of the folder list area and the “evernote” like file list area

### ISSUE THREAD

**Issue by TfTHacker** [ozntel/file-tree-alternative#25]
First, amazing plugin. So nicely done!

I don’t have many folders and would prefer to see more files listed. My request is to make the height of the sections in the view adjustable, so that I can display more files.

Of course drag and drop of the bar that separates the would be the nice, but even some value to set in settings, such a percentage of height, or lines to show in the explorer section, leaving the rest to be files.

Thanks!

**Comment by ozntel** [comment]
Resizing the panes is available already using the separator. Did you give a try?

**Comment by TfTHacker** [comment]
Ok. I did try, but I am on iPad. So had to be more specific when doing the drag. Thanks!

**Comment by ozntel** [comment]
I will also try to implement resizing for mobile in a near future. It doesnt work right now since I just added observer for click. Mobile needs to have touch observer. Additionally, Maybe I can try to implement a way to make size consistent when you restart your vault since right now it starts always with %50 height.
Thanks for bringing up!

**Comment by TfTHacker** [comment]
Thank you for your quick response. I do like the idea of it remembering the position on restart.

FYI: I am able to resize using the trackpad on the magic keyboard. So at least I have a partial solution :-)

**Comment by ozntel** [comment]
@TfTHacker Just FYI - I just released a version and the plugin now remembers the last used height within following relaunch of the leaf or app

**Comment by TfTHacker** [comment]
Wonderful. Thank you! this is very useful.
