### ISSUE TITLE
Different sort criteria

### ISSUE THREAD

**Issue by JodliDev** [ozntel/file-tree-alternative#26]
Hello

Would it be possible to have an option to sort by different criteria?
At the moment, files are sorted by name. It would be very useful to be able to sort by "last changed", so that files that have been recently changed would be at the top of the list.

As far as I can see in the source, that should be quite easy to implement by changing `name` to something else:
https://github.com/ozntel/file-tree-alternative/blob/cf62384a1e2707503a50237041f44fd0d917bec9/src/components/FileView/FileComponent.tsx#L119
(and adding a UI for that option ofcourse)

Thank you for your hard work :)

**Comment by JodliDev** [comment]
Btw there are probably better solutions with less function calls, since I have no experience with obsidian plugins (or typescript), but maybe this is a good starting point:

In my local plugin (minified) installation I changed the equivalent of the line
https://github.com/ozntel/file-tree-alternative/blob/cf62384a1e2707503a50237041f44fd0d917bec9/src/components/FileView/FileComponent.tsx#L119
to
```typescript
 sortedfileList = sortedfileList.sort((a, b) => String(new Date(b.stat.mtime).toISOString()).localeCompare(String(new Date(a.stat.mtime).toISOString()),"en",{numeric:!0}));
```

and now files are sorted by their modified date with the newest file at the top.

**Comment by ozntel** [comment]
It is within the last release. Let's see if it creates any performance issue for anyone. I needed to add additional event listener for `modify` to ensure that the list is updated once any file's content is modified
