### ISSUE TITLE
[Enhancement] Could there be a toggle directly in the file-list to control show/hide files in sub-folders...

### ISSUE THREAD

**Issue by claremacrae** [ozntel/file-tree-alternative#27]
I came here to say thanks for this plugin, and please would you consider adding a button in the file listing, to directly turn off and on files in sub-folders...

It seems like there is space for a new button:

<Img src="https://user-images.githubusercontent.com/4840096/137110811-2030871c-9dbf-4573-817f-45d338fd63e3.png" width="300">

This would behave exactly the same as the setting "Include files from sub-folders to the file list" setting - but remove the need to break the flow to go in to the settings and back out again...

If you would be comfortable with having this but don't have time to do it, I would offer making this my first PR to a plugin, as I think lots of users would likely appreciate it.

It turns out I am echoing this comment from an earlier ticket:

> Neat! That certainly helps! I wonder if it could be a quicker toggle than going all the way to the config? Hotkeyable, for example?

_Originally posted by @Trinsec in https://github.com/ozntel/file-tree-alternative/issues/10#issuecomment-864405571_

**Comment by ozntel** [comment]
The version I just released adds a feature to remember the last active folder you had. It also solves the issue you mentioned above:

> It seems now that when I change the toggle in settings, the panel listing files disappears.
