### ISSUE TITLE
Could there be a command equivalent to "Reveal active file in navigation" 

### ISSUE THREAD

**Issue by claremacrae** [ozntel/file-tree-alternative#31]
### Background

For the built in File Explorer, there is the command "Reveal active file in navigation" .

This is useful in situations where you have already opened a note, such as via "Quick Switcher", or "Recent Files", or following a link, or any other ways...

And then you want to see it in the Navigator, perhaps to open nearby files... There are many other reasons to do this.

The JetBrains IDEs call it "Select Open File" and it has a really convenient icon at the top of their Project view - which is their analog of the Navigator...

![image](https://user-images.githubusercontent.com/4840096/137601604-2bd6ab98-62e4-4330-a6ae-80799a4e7822.png)

### Request

For those who mainly use the File Tree - or switch often between Navigator and File Tree, depending on context, it would be really helpful to also have a command something like **"Reveal active file in File Tree"**.

### Suggested detail

This would do the following (in no particular order):

- Load the File Tree pane
- for the folder view:
    - Expand the folder view, to mark/select the folder containing the active file
    - Scroll the folder view, to ensure the selected folder is visible
- for the file list:
    - Mark/select the name of the active file
    - Scroll the file list, to ensure the selected file is visible

I think effectively it's saying:

Whatever the contents of the File Tree looks like if someone has browsed to a folder and opened a file - that's what it should look like if someone opened the active file via a different route, and then said "Reveal active file in File Tree".

For the icon: A target-like icon for the new command - similar to the JetBrains image above - would be familiar to many users of the JetBrains tools.

**Comment by ozntel** [comment]
It is available in the new release. Please let me know if you encounter any issue.

**Comment by claremacrae** [comment]
> It is available in the new release. Please let me know if you encounter any issue.

Thanks. I updated but couldn't see any change.

**Comment by ozntel** [comment]
You should be able to see the button below. I just downloaded from Community Plugin and it pulls correctly:

![image](https://user-images.githubusercontent.com/55187568/149593018-053a11d5-e66a-40ff-86f7-146d59687645.png)

**Comment by claremacrae** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/4840096/149593309-9973782b-d128-4330-8d8e-b2f1d0caed47.png)

**Comment by claremacrae** [comment]
And with the built-in theme:

![image](https://user-images.githubusercontent.com/4840096/149593438-1f6507f5-fbbd-48ec-906d-771f4af46c26.png)

**Comment by ozntel** [comment]
You need to have file pane active by clicking any folder. The button is on the left side of existing buttons (hide/unhide sub-folders, search, create note). For the moment there is no button on the top of folder pane

**Comment by claremacrae** [comment]
Got it - thanks. I don't think I would have figured that out, I had a file open and was wanting to navigate to the folder with that file...

The ticket is closed, so I'm guessing you did add a command for this... If so, what's the command name please, and then I'll use Customisable Sidebar/Ribbon to bind a button to it....

**Comment by claremacrae** [comment]
> The ticket is closed, so I'm guessing you might have added a command for this... If so, what's the command name please, and then I'll use Customisable Sidebar/Ribbon to bind a button to it....

Don't worry if not...

**Comment by ozntel** [comment]
I'm working on an additional command, which you can use in Customizable Sidebar, and a custom event that you can call from window object anywhere you want programmatically. It should be ready tomorrow

**Comment by ozntel** [comment]
The additional command is also available in the new release. You can assign in Customizable Sidebar. 

You can also use the custom even in case you want to do it programmatically:

```ts
let event = new CustomEvent('file-tree-alternative-reveal-file', {
    detail: {
        file: plugin.app.workspace.getActiveFile(),
    },
});
window.dispatchEvent(event);
```

You need to pass the file, which you want to reveal in the file tree view.

Hope it helps
