### ISSUE TITLE
[Proposal] make tag:XXX and all:XXX respect active Focused Folder

### ISSUE THREAD

**Issue by alexgeirby** [ozntel/file-tree-alternative#32]
Hi!
Thanks for new Focus on Folder feature, its really cool. 
Perhaps it would be more logical to limit the search to only the focused directory and its descendants, do you think?

**Comment by ozntel** [comment]
You have the option now available in the plugin. Just remember to turn on "All & Tag Search only in Focused Folder" option from the plugin settings.
