### ISSUE TITLE
Folders added into excluded folders via  context menu doesn't  appear in section in settings, files still visible

### ISSUE THREAD

**Issue by danieltomasz** [ozntel/file-tree-alternative#34]
Great plugin, it is really useful.
Hoever I have a small problem.
Folders added into excluded folders via  context menu doesn't  appear in the  section "Excluded folders" in settings, 
and files contained in the excluded  folders are  still visible in the "preview" second window, when opening containing it folder

Below I exluded folder where I build pdf via Pandoc and TeX, all temporary files are still visible 
![image](https://user-images.githubusercontent.com/7980381/138238172-98b51a83-5af2-422f-94d8-c1131e9119b6.png)

**Comment by ozntel** [comment]
The files are now filtered within the file list pane before displaying. Any file under excluded folders are not going to be listed. Kindly update to the latest version.

**Comment by danieltomasz** [comment]
Thank you!
