### ISSUE TITLE
File and Folder names not visible when the current Theme is light but sidebar is dark

### ISSUE THREAD

**Issue by vortexmak** [ozntel/file-tree-alternative#37]
I'm using the Red Graphite theme  which is a light theme but the sidebar is dark. 
The fonts color used by Folder Tree is also dark so none of the folder names a re visible

**Comment by ozntel** [comment]
I can not change only for a single theme. But you can overwrite the color within your custom snippet. Default is below:

```css
.oz-folder-name{
    color: var(--text-normal)
}
```

You can just change color to "white" and it should do the job.

**Comment by vortexmak** [comment]
Hey, 
Sorry, I can't find where this change is supposed to be done. Where are the plugins stored?
I'm on linux btw.

Thanks

**Comment by ozntel** [comment]
> Hey, Sorry, I can't find where this change is supposed to be done. Where are the plugins stored? I'm on linux btw.
> 
> Thanks

You need to add in your custom CSS snippet. You can read more in forum how you can add custom styling
