### ISSUE TITLE
keyboard support?

### ISSUE THREAD

**Issue by zeltak** [ozntel/file-tree-alternative#38]
Hi and thx for this great plugin

is it possible to ask for even limited keyboard support like the up/down keys to move forward and backwards in the file list?

best

Z

**Comment by ozntel** [comment]
It is not possible at the moment with the current setup. Each click activates the file, which means focus is shifted to the editor or file preview, hence, Obsidian won't listen the key downs from the file tree plugin view anymore. Thanks for the suggestion anyway
