### ISSUE TITLE
Hints for icon buttons

### ISSUE THREAD

**Issue by gchegr** [ozntel/file-tree-alternative#45]
While it is most obvious for the developer, it is really not clear what all the buttons without captions do. Hovering a cursor over one doe not display a hint label, like all native buttons in Obsidian do. This prevent me from experimenting — what happens if I press the X mark to the left of the folder? Does it delete the folder or removes it from the list, or does it do something else entirely? I don’t know.

**Comment by ozntel** [comment]
Included tooltip for each button in the new release

**Comment by N3C2L** [comment]
@ozntel 

I can't see tooltips when hovering each button.
If you don't mind, please add tooltips when hovering over filenames too or a add a wrap text button option in the toolbar.

**Comment by N3C2L** [comment]
I can use this snippet for the native obsidian file explorer to wrap text (useful for displaying long file titles):

.workspace-leaf-content[data-type=file-explorer] .nav-file-title-content, .workspace-leaf-content[data-type=file-explorer] .nav-folder-title-content {
    display: inline-block;
    overflow-wrap: anywhere;
    overflow: hidden;
    border-left: solid 0.1px;
    white-space: normal;
    text-overflow: ellipsis;
    border-bottom: solid 0.1px;
}

But if I reuse this snippet for the file tree alternative classes, it's not wrapping correctly:

.oz-nav-file-title .oz-nav-file-title-content {
    display: inline-block;
    overflow-wrap: anywhere;
    overflow: hidden;
    border-left: solid 0.1px;
    white-space: normal;
    text-overflow: ellipsis;
    border-bottom: solid 0.1px;
}

@ozntel Can you help me here, pleasee?
