### ISSUE TITLE
Slight lag every few seconds when typing

### ISSUE THREAD

**Issue by thomasvs** [ozntel/file-tree-alternative#47]
Similarly to #39 I experience a slight lag every few seconds when typing.  I had 71 plugins active and bisected it down to this one, disabling half of them each try.

Here's a screencast that shows it.

https://user-images.githubusercontent.com/248196/148444755-b9bd3daf-645a-4a5d-89a7-75acbb95b5f6.mp4

**Comment by ozntel** [comment]
Can you try if it is still the same? I just released a version, which should reduce the number of updates drastically

**Comment by ozntel** [comment]
The last release hopefully should solve the problem but let me know if the issue still persists

**Comment by ottsch** [comment]
Same problem here with latest version
