### ISSUE TITLE
Cannot create a folder via the alternative tree

### ISSUE THREAD

**Issue by thatdwayne** [ozntel/file-tree-alternative#48]
When I right-click on a folder and select "new folder," nothing happens.
Obsidian v0.13.19

**Comment by ozntel** [comment]
Yes, you are right actually. It was caused by the last update. I missed updating some of the parameters. The last release should solve the issue.

**Comment by ozntel** [comment]
> I know how to create a folder as a subfolder under current folders in the root by right-click
> 
> but it seems that there’s no way to create folder in the root via this plugin? (I have a good back to default file browser to create it; which is ok. But I hope I can create folder directly in this plugin, avoiding switching panel)

You can enable the Root Folder from the plugin settings (Show Root Folder option)
And then you can create a new folder under the root folder.

![image](https://user-images.githubusercontent.com/55187568/154483563-c93cc439-dd0a-41b0-9483-2ba0a25e9a1b.png)

**Comment by realliyifei** [comment]
I know I can set showing root folder, but then the panel would look more cumbersome.

Perhaps adding button “create folder in current root” is not too hard? 

And it’s intuitive: both macOS finder and obsidian default file explorer contains this function

**Comment by ozntel** [comment]
> thank you! I know I can set showing root folder, but then the panel would look more cumbersome.

It is available in the new release
