### ISSUE TITLE
[FR] Collapse/expand all folders at once

### ISSUE THREAD

**Issue by Trinsec** [ozntel/file-tree-alternative#49]
Could there be an option added to collapse/expand all the folders at once? It could be a right-click menu option so that only that folder you rightclicked and its subfolders will be affected by the action?

It could be like this: 
- Expand all folders
- Collapse all folders
- Expand all subfolders
- Collapse all subfolders

**Comment by DannyQuah** [comment]
I'd greatly value this too.

**Comment by ih8snow** [comment]
Very good point, the other plugin "collaps all" does not work in combination with this plugin

**Comment by ozntel** [comment]
It is available in the new release

**Comment by ih8snow** [comment]
Super!
