### ISSUE TITLE
[Bug] Long folder name covers filenames

### ISSUE THREAD

**Issue by Trinsec** [ozntel/file-tree-alternative#50]
![image](https://user-images.githubusercontent.com/577738/149238058-61d243d4-869b-40b5-8d2e-4caaddf79be2.png)
As you can see in the attached image, long folder names wraps around on top of the filenames. Maybe a nice solution could be to cut off the long folder name (and it'd show the full folder name when you hover over it).

**Comment by ozntel** [comment]
It should be fixed in the new release
