### ISSUE TITLE
Request: Add ability to drag a file to a note, like the built in file tree/explorer

### ISSUE THREAD

**Issue by Hunanbean** [ozntel/file-tree-alternative#52]
Request: Add ability to drag a file to a note, like the built in file tree/explorer

**Comment by ih8snow** [comment]
Support this one, without this option it's really difficult to move the notes in an easy way.
i.e. I need to select 5 files in a folder and simply move them to a new destination folder.
I know how to do that one after the other…but that’s not smart 

Anybody a better for a workaround

**Comment by ih8snow** [comment]
Actually just noted that I can't drag a note from the file explorer to a note in edit mode, for example when I want to creat a link.

Not sure why this is not working, but I really think this is a must.

**Comment by ozntel** [comment]
This feature is available in the new release. You can drag the file to Editor and it will create automatically a link to the file dragged
