### ISSUE TITLE
possible to see .dotfiles and hidden folders?

### ISSUE THREAD

**Issue by kleerkoat** [ozntel/file-tree-alternative#53]
i've been searching for days to see if this is possible. i don't think it's possible but you're an obsidian plugin guru, maybe you know. thanks

**Comment by ozntel** [comment]
Honestly speaking I don't know if there is a way to get the list of hidden files or folders. I haven't seen myself. You can ask to `lishid` on Discord if he included or has a plan to include in the API in the future.
