### ISSUE TITLE
[Bug] Parent folder doesn't show note count

### ISSUE THREAD

**Issue by Trinsec** [ozntel/file-tree-alternative#55]
The parent folder can contain notes too, and the count isn't shown for that one in the folder list when it's expanded.

![image](https://user-images.githubusercontent.com/577738/150840718-f498096b-ac00-4f1d-be8f-a40ca83e88ca.png)

![image](https://user-images.githubusercontent.com/577738/150840915-6bd22cce-54b9-4d57-91ba-814dda47bc50.png)
The Affinity folder itself has 9 notes but it isn't being shown here.

**Comment by ghanan** [comment]
I'd also like to see the count of notes in the parent folder.

**Comment by ozntel** [comment]
It was actually on purpose. But I changed in the new version. You should also see the number of notes/files under the expanded folder.
