### ISSUE TITLE
Request: Add ability "Open in new pane"

### ISSUE THREAD

**Issue by aycajr** [ozntel/file-tree-alternative#59]
Please add the ability for us to while using the 'File Tree' plugin to be able to open the file on a new pane just like the default folder structure allows. Thanks.

**Comment by ozntel** [comment]
It was available but only for mobile. I opened for Desktop, as well. You can see "Open in a New Pane" in Context Menu.
In addition to the button, you should be able to open in a new window using Ctrl button and clicking the name of the file.
