### ISSUE TITLE
[Enhancement] Add data path for folder

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/file-tree-alternative#6]
If it's possible, as in the original file tree, add a way to add some specific CSS to a folder.
For example, in the original folder tree, I can add some icon with this css : 
```css
.nav-folder-title[data-path^="1. Archive"] .nav-folder-title-content::before
.nav-folder-title[data-path^="1. Archive/Fiches"] .nav-folder-title-content::before {
```

I can also change the icon for normal file, extern file with : 
```css
.nav-file-title[data-path*="10. Template/Templater"] .nav-file-title-content:only-child:before,
.search-result-collapse-indicator+span:before,
.nav-file-icon:before 
```

**Comment by ozntel** [comment]
It will be included in the next release

**Comment by ozntel** [comment]
Version released, you can update the plugin from the community plugins
