### ISSUE TITLE
[feature request] Custom workspace

### ISSUE THREAD

**Issue by cs-mshah** [ozntel/file-tree-alternative#62]
By workspace I mean just showing an included list of folders (and all their sub-folders). This is a better alternative to exclude folder paths option as I might just want certain folders to be shown in my changing root directory. All I would do is include a list of folders that should be shown in the file tree. If this filed is non-empty, only these folders should be shown.

**Comment by ozntel** [comment]
You can use the focus on folder option to view only the folder that you want to see. Thanks!
