### ISSUE TITLE
Mac OS delete file can't recover

### ISSUE THREAD

**Issue by KeiraZ** [ozntel/file-tree-alternative#65]
If I delete the files with the file-tree-alternative plugin, the deleted file does not go into the Obsidian trash or the system's Trash. So I cannot find or recover the deleted files.

Obsidian Version: v0.13.31. Mac OS Version: macOS Monterey Version 12.2.1

**Comment by ozntel** [comment]
In the new version, you can change the default behaviour of delete button. It was deleting permanently before. Now you have options to send to obsidian trash or system trash. Hope it helps
