### ISSUE TITLE
feature request: sort by file size

### ISSUE THREAD

**Issue by eleanorkonik** [ozntel/file-tree-alternative#67]
I was messing around with a new [word count plugin](https://github.com/isaaclyman/novel-word-count-obsidian) and it made me realize how much I'd love to sort my files by size. Right now I use dataview to find my most mature files to work on, but I'd love to just do this from the file tree itself...

**Comment by ozntel** [comment]
Sorting by file size is available in the new release, which I just pushed. 
I also moved sorting options from plugin settings to file list pane to make it easy to switch between different sorting options:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/55187568/158038233-eb468a56-d710-4d4d-9ddb-2316eb8fe3e8.png">

**Comment by eleanorkonik** [comment]
thank you so much this is incredible!
