### ISSUE TITLE
Request: Drag note to new folder without detour

### ISSUE THREAD

**Issue by Hunanbean** [ozntel/file-tree-alternative#72]
As it is right now, i have to drag a note out and over the display portion of the screen, then back on to the file tree in order to move a note from one folder to another. I had expected to just be able to drag directly upwards to a new folder. So, requesting the ability to drag a note directly Up to a new folder instead of detouring through the display portion of the screen.

Thank you

**Comment by ozntel** [comment]
Please check https://github.com/ozntel/file-tree-alternative/issues/42#issuecomment-1079716104
