### ISSUE TITLE
Preview files only with CTRL

### ISSUE THREAD

**Issue by ThomasOrlita** [ozntel/file-tree-alternative#74]
This is the behaviour of the built-in File Explorer plugin, it'd be awesome if it worked the same with this plugin as well. Now it's you either don't get previews at all or get them all them time when hovering over files.

https://github.com/ozntel/file-tree-alternative/issues/23#issuecomment-939295946_

**Comment by ThomasOrlita** [comment]
I've created a draft (#75), from a quick testing, it should work, but I haven't tried to build the project.

**Comment by ozntel** [comment]
It is available in the new release. I needed to twick a little bit so that it works in both Mac and Windows. Also your condition was with "Or". It needs to be "And" to make sure that both settings preferences and control key is checked during the event fire.
Thanks for your suggestion

**Comment by ThomasOrlita** [comment]
Thanks, it works in the new release. I used "or" to allow it to work either while holding the key (regardless of the setting), or without needing to hold the key (with the setting enabled). But the "and" way is fine as well.

One caveat is that this is bound to a mouse enter listener only, so this won't work in the following scenario (this works correctly in the build-in File Explorer plugin):
1. Position mouse pointer over a file
2. Hold CTRL

I can't think of an straightforward way to fix this as key and mouse events are distinct events.
