### ISSUE TITLE
Clicking on a file name with the # character in the name creates a new note and doesn't display the selected note.

### ISSUE THREAD

**Issue by Merlin9999** [ozntel/file-tree-alternative#76]
Hello, and thanks for a great plug-in!

I didn't notice another similar issue. Hopefully, this isn't a dupe.

As a software developer that uses the c# programming language, sometimes my notes have "c#" as part of the note's file name. When clicking on that note in the split file listing, it does not display, and a new empty note is created instead. For example, clicking on a note named "Async Best Practices in C# and Visual Basic" will create a new empty note named "Async Best Practices in C" instead of selecting and displaying the existing non-empty note.

Thank-You for your time.

**Comment by ozntel** [comment]
It should be fixed in the new release

**Comment by Merlin9999** [comment]
> It should be fixed in the new release

Confirmed. Thanks again!
