### ISSUE TITLE
[FR] Add an option to enable delete conformation dialog when ursers deleting files.

### ISSUE THREAD

**Issue by XMB-7** [ozntel/file-tree-alternative#77]
As the title suggests. Sometimes intend to rename a file but accidentally delete it when selecting the wrong command, sometimes even without awareness if clicking so fast, thus a delete confirmation would be much helpful to prevent this. Thanks.
![图片](https://user-images.githubusercontent.com/65625632/163099952-e848d7a0-f8c3-4544-8756-2c11d089a965.png)

**Comment by egeesin** [comment]
I second this. Also I'd like to have an option to hide delete button next to the filename. I'd prefer to simply right-click on it if I intend to delete it rather than accidentally moving it to trash.

**Comment by ozntel** [comment]
It is available in the last release. Please update plugin to v.2.2.6. Thanks!
