### ISSUE TITLE
[BUG] Auto reload another folder files

### ISSUE THREAD

**Issue by tinyblckc00000al** [ozntel/file-tree-alternative#79]
When I click a folder , the file view always somehow reload  notes in few seconds as another folder I clicked before and always the same folder.

**Comment by ozntel** [comment]
I can not help much if there is no recording or detailed information how it is triggered, which conditions etc. The plugin is being used for many users, most probably there is something unique in your vault that triggers this issue. Thanks!

**Comment by ozntel** [comment]
I am closing it but let me know if the issue persists. Thanks

**Comment by tinyblckc00000al** [comment]
Thanks for your attention. But the problem disappear now. And I have updated this plugin to the latest release. I don't know if that has something to&nbsp;do with it, or just my vault went wrong. If the problem happens again, I'll try to record the debug infos.



------------------&nbsp;Original&nbsp;------------------
From: "Ozan ***@***.***&gt;; 
Date: 2022年5月3日(星期二) 晚上7:14
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [ozntel/file-tree-alternative] [BUG] Auto reload another folder files (Issue #79)





 
I am closing it but let me know if the issue persists. Thanks
