### ISSUE TITLE
[Bug] Number arranged in alphabetical order

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/file-tree-alternative#8]
Normally, number are arranged by number, as : 1/2/3....n.
But, in the plugin, there are like text, and arranged by 1/10/11/12 - 2/20/21....
![image](https://user-images.githubusercontent.com/30244939/121888114-e2538b80-cd17-11eb-8658-442a89906343.png)
![image](https://user-images.githubusercontent.com/30244939/121888130-e5e71280-cd17-11eb-8a2b-0c396c9bd88b.png)
I use number to class my file, so it's a problem for me to have that. Maybe add a classification option?

**Comment by ozntel** [comment]
I just release a version, in which I changed the `sorting` algorithm. It should be ok now.
