### ISSUE TITLE
Moving Notes from Filetree Explorer view into  other notes creates wikilink with subfolder

### ISSUE THREAD

**Issue by ih8snow** [ozntel/file-tree-alternative#80]
Sorry for the strange description in the titel.

With your update we can move a note (link) from the file tree explorer into a note and when the (linked) notes is within a subfolder it looks like this `[[001-Projects/Projekt Übersicht]]`
Note: I move this link into a new note in the same folder! So the info on the folder is not needed here.

When I use the original file explorer, it creates a (nicer/shorter) link for the same note: `[[Projekt Übersicht]]`

Would be great if you can check that!.
Many thanks

**Comment by ozntel** [comment]
It depends on your settings:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/55187568/164972560-6dbfbcc8-3e23-4cb5-abd7-f1fb8d0c5f2e.png">
