### ISSUE TITLE
Minimal Theme - how to adjust the settings

### ISSUE THREAD

**Issue by ih8snow** [ozntel/file-tree-alternative#81]
I'm using minimal theme in light mode with "nord color scheme".
I noticed two issues here:
- in the relatively dark side bar the count of notes is not readable because of the text color
- The title of the notes in the file area are in black text color, which makes it difficult to read (folders are much brighter in the text color).

I guess this is linked to settings in Minimal Theme, so can you help me to figure out where this text color for this two areas is listed?

In dark mode it's ok and everything is readable.
![image](https://user-images.githubusercontent.com/82544852/164973462-c3693485-2164-48bf-9f10-42637721ef1f.png)

**Comment by ozntel** [comment]
I just released a new version, which should help with the coloring. I fixed them to '--text-muted'

**Comment by ih8snow** [comment]
Top!
Thanks!
