### ISSUE TITLE
Support of Style Settings

### ISSUE THREAD

**Issue by pcause** [ozntel/file-tree-alternative#82]
It would be very useful to have the css annotated so that it is easier to style the display using the Style Settings plugin

**Comment by ozntel** [comment]
Honestly speaking I didn't understand much what you mean. Can you expand it more?

**Comment by pcause** [comment]
Sorry.  There is a plugin called Style Settings.  It has an easy way to change the theme settings or plugin settings for themes/plugins that support it.  here is the URL [style settings](https://github.com/mgmeyers/obsidian-style-settings).  It makes it easy to create changes to the display styles without using CSS snippets.  It requires you set up the CSS file a certain way.

I wanted to change the display of the file list pane of a folder (the bottom pane) because I use topaz and the file title uses:

```css
color: var(--text-muted);
```

and the text is hard to read.

**Comment by 9527blues** [comment]
yep,  font size of the filename seem a little small for me

**Comment by peterjbraam** [comment]
May I vote +1 for customizable font size please? Thanks for the fantastic plugin.

**Comment by jerviscui** [comment]
Can you support horizontal scroll bars panels that are not wide enough to display the full content?

**Comment by ltroj** [comment]
+1 Please make the css attributes available in the Style Settings plugin.

**Comment by ozntel** [comment]
It is available in the new release. Please make sure that you update to the latest version `v.2.3.2` Thanks

**Comment by ltroj** [comment]
@ozntel Thanks for implementing, makes it much easier to make the file tree blend in with different themes!
