### ISSUE TITLE
Rename routine is doing way too much work

### ISSUE THREAD

**Issue by nickmilo** [ozntel/file-tree-alternative#83]
Recently, when I rename folders (esp folders with subfolders), Obsidian freezes. Thanks to @lishid we figured out it is coming from File Tree Alternative. This link points to where the problem is:

https://github.com/ozntel/file-tree-alternative/blob/aebc37b9c8c9a036ef3e73633b81ea717133a629/src/components/MainView/MainComponent.tsx#L222

**Comment by ozntel** [comment]
Could you try to see if the last release helps? I reduced the number of updates after each vault change and it should help with the performance

**Comment by nickmilo** [comment]
Yep, that seems to have solved the previous issue
