### ISSUE TITLE
Need a possibility to create a new note from a template

### ISSUE THREAD

**Issue by ih8snow** [ozntel/file-tree-alternative#85]
Hi,
currently, I can only create a new blank standard note via the icon list in the filearea.
When I need to use a template (which I nearly always do), I need to add the template "over" the then existing page.
As I'm just creating a manual for my team, I noticed that this process could be much easier.

Could you offer the possibility to directly add a new note into the given folder with a selected template (i.e. show the list of templates as selection or similar?)

I'm working with the very popular templater plugin, so it would be cool to have something lie "Create new note from template" as a button !

Thanks!

**Comment by ozntel** [comment]
The relevant plugin automatically adds this button since File Tree Alternative extends the default context menu of Obsidian. If you right-click the folder name,  you should have it. Thanks!
