### ISSUE TITLE
[BUG] Working file disapears from file list

### ISSUE THREAD

**Issue by neurosock** [ozntel/file-tree-alternative#88]
When 'show files from sub-folders' and 'sorting by last update' are enabled, the working file disappears from file list when it is updated. This seems to happen after a few seconds of modifying the file (maybe when Obsidian saves the file?). The fist time you modify a file after opening the vault this doesn't happen. It happens only after a second file is modified. Then it happens consistently. Hiding and showing sub-folders again recovers the file list. This doesn't occur when sorting by name.
OS: Windows 10
Obsidian: 0.14.6
Plugin: 2.1.1

**Comment by ozntel** [comment]
I have never seen this issue, honestly speaking. Is it still the same after the updates? If so, it might be caused by something that you have in your vault and it would require more investigation.

**Comment by ozntel** [comment]
I assume this is not the case anymore. Let me know in case the issue persists. Thanks

**Comment by neurosock** [comment]
Dear [ozntel](https://github.com/ozntel) the issue still persists as the newest version (2.3.3) but seems to require certain things to be enabled for it to happen. I have here a list of steps that may help reproduce it on your side:
OS: Windows 10
Obsidian: 1.1.16
Installer: 0.15.9
Plugin: 2.3.3

- Create new vault
- Install plugin
- With default settings, in the file panel set "Show files from sub-folders" and sort by last update
- Create the following file structure
```
    folder0
        test3.md
        test4.md
    folder1
        test5.md
        test6.md
    test0.md
    test1.md
    test2.md
```
- Modify any files from the root folder, no problem observed
- Modify any files from the sub-folders, sub-folder files disappear from list

Here a short gif of the effect. You can see how test6.md and test5.md disappear from the list 
![FTABug0](https://user-images.githubusercontent.com/76121344/226563144-0381c2ae-bad3-4148-b145-df06eaeca959.gif)

Thanks!
