### ISSUE TITLE
Could you please add a horizontal layout?

### ISSUE THREAD

**Issue by Jingzhenzxz** [ozntel/file-tree-alternative#90]
Hello! Could you please add a horizontal layout? : )

![image](https://user-images.githubusercontent.com/47069834/170481774-1ed71379-64e4-4f5d-a91f-089a29111052.png)

**Comment by ozntel** [comment]
Hi, unfortunately, it is not in my plans to implement a horizontal view. There is a quite limited place within the sidebar, that's why I implemented the vertical. Thanks for the suggestion
