### ISSUE TITLE
The tree view is not updated when a creating a new note

### ISSUE THREAD

**Issue by ma-sadeghi** [ozntel/file-tree-alternative#98]
When creating a new note, the tree view is not instantly updated. In fact, it won't update until you manually click on a different folder and then click on the original folder.

**Comment by ma-sadeghi** [comment]
I just noticed that the issue persists if you add a new folder (it won't show up until you restart Obsidian).

**Comment by wedgiebee** [comment]
I've been experiencing this also. Any ideas @ozntel ?

**Comment by ozntel** [comment]
Are you on the recent version of the plugin?

**Comment by ma-sadeghi** [comment]
@ozntel Yes, I'm using the most recent version of the plugin. I just checked again, and the issue still persists.

**Comment by ozntel** [comment]
I am not sure if it will solve your issue but I just released a new version that fixes a related issue. The files moved to the active folder was not displayed as you mentioned. Please check and let me know if this release fixes your concern

**Comment by ma-sadeghi** [comment]
@ozntel Great, it worked just fine! Thank you!
